spring:
  application:
    title: Indicadores
    name: Indicadores
  profiles:
    active: dev
  neo4j:
    uri: bolt://localhost:7687/neo4j
    authentication:
        username: neo4j
        password: Indicadores@

application:
    name: Indicadores
    version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /indicadores-api